apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: python-api
        image: registry.gitlab.com/teedeemicro/python-api:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: python-api
spec:
  selector:
    app: python-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001