apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleepy-api
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleepy-api
  template:
    metadata:
      labels:
        app: sleepy-api
    spec:
      containers:
      - name: sleepy-api
        image: registry.gitlab.com/teedee22/sleepy-api
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: sleepy-api
spec:
  selector:
    app: sleepy-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001